[workspace]
members = [
    "crates/gorgondb",
    "crates/medusadb",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/medusadb/medusadb.git"
publish = true

[workspace.dependencies]
gorgondb = { version = "0.0.1", path = "crates/gorgondb" }
medusadb = { path = "crates/medusadb" }

base85 = "2.0.0"
blake3 = "1.4.1"
byteorder = "1.4.3"
bytes = "1.4.0"
rmp-serde = "1.1.2"
serde = "1.0.183"
serde_json = "1.0.105"
serde_with = "3.3.0"
thiserror = "1.0.47"
