
# cargo-vet audits file

[[audits.gorgondb]]
who = "Julien Kauffmann <julienkauffmann85+github@gmail.com>"
criteria = "safe-to-deploy"
version = "0.0.1"

[[audits.medusadb]]
who = "Julien Kauffmann <julienkauffmann85+github@gmail.com>"
criteria = "safe-to-deploy"
version = "0.0.1"

[[audits.medusadb]]
who = "Julien Kauffmann <julienkauffmann85+github@gmail.com>"
criteria = "safe-to-deploy"
version = "0.0.1"

[[audits.medusadb]]
who = "Julien Kauffmann <julienkauffmann85+github@gmail.com>"
criteria = "safe-to-deploy"
version = "0.0.1"

[[trusted.aho-corasick]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-03-28"
end = "2024-12-28"

[[trusted.anstream]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-16"
end = "2024-12-28"

[[trusted.anstyle]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-05-18"
end = "2024-12-28"

[[trusted.anstyle-parse]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-08"
end = "2024-12-28"

[[trusted.anstyle-query]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-04-13"
end = "2024-12-28"

[[trusted.anstyle-wincon]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-08"
end = "2024-12-28"

[[trusted.anyhow]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-05"
end = "2024-12-28"

[[trusted.async-trait]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-07-23"
end = "2024-12-28"

[[trusted.aws-config]]
criteria = "safe-to-deploy"
user-id = 160111 # AWS SDK Rust Bot (aws-sdk-rust-ci)
start = "2022-06-22"
end = "2024-12-28"

[[trusted.aws-credential-types]]
criteria = "safe-to-deploy"
user-id = 160111 # AWS SDK Rust Bot (aws-sdk-rust-ci)
start = "2022-12-29"
end = "2024-12-28"

[[trusted.aws-http]]
criteria = "safe-to-deploy"
user-id = 160111 # AWS SDK Rust Bot (aws-sdk-rust-ci)
start = "2022-06-22"
end = "2024-12-28"

[[trusted.aws-runtime]]
criteria = "safe-to-deploy"
user-id = 160111 # AWS SDK Rust Bot (aws-sdk-rust-ci)
start = "2023-04-06"
end = "2024-12-28"

[[trusted.aws-sdk-dynamodb]]
criteria = "safe-to-deploy"
user-id = 160111 # AWS SDK Rust Bot (aws-sdk-rust-ci)
start = "2022-06-22"
end = "2024-12-28"

[[trusted.aws-sdk-s3]]
criteria = "safe-to-deploy"
user-id = 160111 # AWS SDK Rust Bot (aws-sdk-rust-ci)
start = "2022-06-22"
end = "2024-12-28"

[[trusted.aws-sdk-sso]]
criteria = "safe-to-deploy"
user-id = 160111 # AWS SDK Rust Bot (aws-sdk-rust-ci)
start = "2022-06-22"
end = "2024-12-28"

[[trusted.aws-sdk-ssooidc]]
criteria = "safe-to-deploy"
user-id = 160111 # AWS SDK Rust Bot (aws-sdk-rust-ci)
start = "2022-06-23"
end = "2024-12-28"

[[trusted.aws-sdk-sts]]
criteria = "safe-to-deploy"
user-id = 160111 # AWS SDK Rust Bot (aws-sdk-rust-ci)
start = "2022-06-22"
end = "2024-12-28"

[[trusted.aws-sigv4]]
criteria = "safe-to-deploy"
user-id = 160111 # AWS SDK Rust Bot (aws-sdk-rust-ci)
start = "2022-06-22"
end = "2024-12-28"

[[trusted.aws-smithy-async]]
criteria = "safe-to-deploy"
user-id = 160111 # AWS SDK Rust Bot (aws-sdk-rust-ci)
start = "2022-06-22"
end = "2024-12-28"

[[trusted.aws-smithy-checksums]]
criteria = "safe-to-deploy"
user-id = 160111 # AWS SDK Rust Bot (aws-sdk-rust-ci)
start = "2022-07-20"
end = "2024-12-28"

[[trusted.aws-smithy-eventstream]]
criteria = "safe-to-deploy"
user-id = 160111 # AWS SDK Rust Bot (aws-sdk-rust-ci)
start = "2022-06-22"
end = "2024-12-28"

[[trusted.aws-smithy-http]]
criteria = "safe-to-deploy"
user-id = 160111 # AWS SDK Rust Bot (aws-sdk-rust-ci)
start = "2022-06-22"
end = "2024-12-28"

[[trusted.aws-smithy-json]]
criteria = "safe-to-deploy"
user-id = 160111 # AWS SDK Rust Bot (aws-sdk-rust-ci)
start = "2022-06-22"
end = "2024-12-28"

[[trusted.aws-smithy-query]]
criteria = "safe-to-deploy"
user-id = 160111 # AWS SDK Rust Bot (aws-sdk-rust-ci)
start = "2022-06-22"
end = "2024-12-28"

[[trusted.aws-smithy-runtime]]
criteria = "safe-to-deploy"
user-id = 160111 # AWS SDK Rust Bot (aws-sdk-rust-ci)
start = "2023-04-06"
end = "2024-12-28"

[[trusted.aws-smithy-runtime-api]]
criteria = "safe-to-deploy"
user-id = 160111 # AWS SDK Rust Bot (aws-sdk-rust-ci)
start = "2023-04-06"
end = "2024-12-28"

[[trusted.aws-smithy-types]]
criteria = "safe-to-deploy"
user-id = 160111 # AWS SDK Rust Bot (aws-sdk-rust-ci)
start = "2022-06-22"
end = "2024-12-28"

[[trusted.aws-smithy-xml]]
criteria = "safe-to-deploy"
user-id = 160111 # AWS SDK Rust Bot (aws-sdk-rust-ci)
start = "2022-06-22"
end = "2024-12-28"

[[trusted.aws-types]]
criteria = "safe-to-deploy"
user-id = 160111 # AWS SDK Rust Bot (aws-sdk-rust-ci)
start = "2022-06-22"
end = "2024-12-28"

[[trusted.byteorder]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-06-09"
end = "2024-12-28"

[[trusted.clap]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2021-12-08"
end = "2024-12-28"

[[trusted.clap_builder]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-28"
end = "2024-12-28"

[[trusted.clap_lex]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-04-15"
end = "2024-12-28"

[[trusted.colorchoice]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-04-13"
end = "2024-12-28"

[[trusted.hashbrown]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2019-04-02"
end = "2024-12-28"

[[trusted.is-terminal]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2022-01-22"
end = "2024-12-28"

[[trusted.itoa]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-05-02"
end = "2024-12-28"

[[trusted.js-sys]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2024-12-28"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2021-01-27"
end = "2024-12-28"

[[trusted.linux-raw-sys]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2021-06-12"
end = "2024-12-28"

[[trusted.memchr]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-07-07"
end = "2024-12-28"

[[trusted.paste]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-19"
end = "2024-12-28"

[[trusted.proc-macro2]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-04-23"
end = "2024-12-28"

[[trusted.quote]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-04-09"
end = "2024-12-28"

[[trusted.regex]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-02-27"
end = "2024-12-28"

[[trusted.regex-automata]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-02-25"
end = "2024-12-28"

[[trusted.regex-lite]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2023-02-28"
end = "2024-12-28"

[[trusted.regex-syntax]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-03-30"
end = "2024-12-28"

[[trusted.rustix]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2021-10-29"
end = "2024-12-28"

[[trusted.ryu]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-05-02"
end = "2024-12-28"

[[trusted.same-file]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-07-16"
end = "2024-12-28"

[[trusted.serde]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2024-12-28"

[[trusted.serde_bytes]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-02-25"
end = "2024-12-28"

[[trusted.serde_derive]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2024-12-28"

[[trusted.serde_json]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-02-28"
end = "2024-12-28"

[[trusted.syn]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2024-12-28"

[[trusted.thiserror]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2024-12-28"

[[trusted.thiserror-impl]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2024-12-28"

[[trusted.unicode-ident]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2021-10-02"
end = "2024-12-28"

[[trusted.walkdir]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-06-09"
end = "2024-12-28"

[[trusted.wasm-bindgen]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2024-12-28"

[[trusted.wasm-bindgen-backend]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2024-12-28"

[[trusted.wasm-bindgen-macro]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2024-12-28"

[[trusted.wasm-bindgen-macro-support]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2024-12-28"

[[trusted.web-sys]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2024-12-28"

[[trusted.winapi-util]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2020-01-11"
end = "2024-12-28"

[[trusted.windows-core]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-15"
end = "2024-12-28"

[[trusted.windows-sys]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-15"
end = "2024-12-28"

[[trusted.windows-targets]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-09"
end = "2024-12-28"

[[trusted.windows_aarch64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2024-12-28"

[[trusted.windows_aarch64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-05"
end = "2024-12-28"

[[trusted.windows_i686_gnu]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2024-12-28"

[[trusted.windows_i686_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2024-12-28"

[[trusted.windows_x86_64_gnu]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2024-12-28"

[[trusted.windows_x86_64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2024-12-28"

[[trusted.windows_x86_64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2024-12-28"
