
# cargo-vet config file

[cargo-vet]
version = "0.8"

[[exemptions.addr2line]]
version = "0.21.0"
criteria = "safe-to-deploy"

[[exemptions.adler]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.android-tzdata]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.android_system_properties]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.anstream]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.anstyle]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.anstyle-parse]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.anstyle-query]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.anstyle-wincon]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.anyhow]]
version = "1.0.75"
criteria = "safe-to-deploy"

[[exemptions.arrayref]]
version = "0.3.7"
criteria = "safe-to-deploy"

[[exemptions.arrayvec]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.async-compat]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.async-trait]]
version = "0.1.73"
criteria = "safe-to-deploy"

[[exemptions.autocfg]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.backtrace]]
version = "0.3.69"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.21.3"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.4.0"
criteria = "safe-to-deploy"

[[exemptions.blake3]]
version = "1.4.1"
criteria = "safe-to-deploy"

[[exemptions.block-buffer]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.bumpalo]]
version = "3.13.0"
criteria = "safe-to-deploy"

[[exemptions.byteorder]]
version = "1.4.3"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.0.82"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.26"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "4.4.1"
criteria = "safe-to-deploy"

[[exemptions.clap_builder]]
version = "4.4.1"
criteria = "safe-to-deploy"

[[exemptions.clap_derive]]
version = "4.4.0"
criteria = "safe-to-deploy"

[[exemptions.clap_lex]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.colorchoice]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.constant_time_eq]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.core-foundation-sys]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.crypto-common]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.darling]]
version = "0.20.3"
criteria = "safe-to-deploy"

[[exemptions.darling_core]]
version = "0.20.3"
criteria = "safe-to-deploy"

[[exemptions.darling_macro]]
version = "0.20.3"
criteria = "safe-to-deploy"

[[exemptions.deranged]]
version = "0.3.8"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.equivalent]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.errno]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.errno-dragonfly]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.fastcdc]]
version = "3.1.0"
criteria = "safe-to-deploy"

[[exemptions.fnv]]
version = "1.0.7"
criteria = "safe-to-deploy"

[[exemptions.fs4]]
version = "0.6.6"
criteria = "safe-to-deploy"

[[exemptions.futures]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.futures-channel]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.futures-executor]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.futures-io]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.futures-macro]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.28.0"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.12.3"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.heck]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.hex]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone]]
version = "0.1.57"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone-haiku]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.ident_case]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "1.9.3"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.9"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.64"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.147"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.10"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.20"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "0.8.8"
criteria = "safe-to-deploy"

[[exemptions.num-traits]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.num_cpus]]
version = "1.16.0"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.32.0"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.18.0"
criteria = "safe-to-deploy"

[[exemptions.parking_lot]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.paste]]
version = "1.0.14"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.13"
criteria = "safe-to-deploy"

[[exemptions.pin-utils]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.66"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.33"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.reflink]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.rmp]]
version = "0.8.12"
criteria = "safe-to-deploy"

[[exemptions.rmp-serde]]
version = "1.1.2"
criteria = "safe-to-deploy"

[[exemptions.rustc-demangle]]
version = "0.1.23"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "0.38.9"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.15"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.183"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.183"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.105"
criteria = "safe-to-deploy"

[[exemptions.serde_with]]
version = "3.3.0"
criteria = "safe-to-deploy"

[[exemptions.serde_with_macros]]
version = "3.3.0"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.1"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.11.0"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.5.3"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.subtle]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.29"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "1.0.47"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "1.0.47"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.25"
criteria = "safe-to-deploy"

[[exemptions.time-core]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.time-macros]]
version = "0.2.11"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.32.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-macros]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-stream]]
version = "0.1.14"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.37"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.26"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.31"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.16.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.11"
criteria = "safe-to-deploy"

[[exemptions.utf8parse]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.87"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.87"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.87"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.87"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.87"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"
