
# cargo-vet config file

[cargo-vet]
version = "0.8"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.gorgondb]
audit-as-crates-io = true

[policy.medusadb]
audit-as-crates-io = true

[[exemptions.addr2line]]
version = "0.21.0"
criteria = "safe-to-deploy"

[[exemptions.ahash]]
version = "0.8.6"
criteria = "safe-to-deploy"

[[exemptions.allocator-api2]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.android-tzdata]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.android_system_properties]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.arrayvec]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.async-compat]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.autocfg]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.backtrace]]
version = "0.3.69"
criteria = "safe-to-deploy"

[[exemptions.base16ct]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.base64-simd]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.base64ct]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.4.1"
criteria = "safe-to-deploy"

[[exemptions.blake3]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.block-buffer]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.bytes-utils]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.cast]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.cc]]
version = "1.0.83"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.31"
criteria = "safe-to-deploy"

[[exemptions.ciborium]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.ciborium-io]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.ciborium-ll]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.clap_derive]]
version = "4.4.7"
criteria = "safe-to-deploy"

[[exemptions.const-oid]]
version = "0.9.6"
criteria = "safe-to-deploy"

[[exemptions.core-foundation]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.core-foundation-sys]]
version = "0.8.6"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.11"
criteria = "safe-to-deploy"

[[exemptions.crc32c]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.criterion]]
version = "0.5.1"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.crossbeam-epoch]]
version = "0.9.17"
criteria = "safe-to-run"

[[exemptions.crossbeam-utils]]
version = "0.8.18"
criteria = "safe-to-run"

[[exemptions.crypto-bigint]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.crypto-bigint]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.darling]]
version = "0.20.3"
criteria = "safe-to-deploy"

[[exemptions.darling_core]]
version = "0.20.3"
criteria = "safe-to-deploy"

[[exemptions.darling_macro]]
version = "0.20.3"
criteria = "safe-to-deploy"

[[exemptions.der]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.deranged]]
version = "0.3.10"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.dirs]]
version = "5.0.1"
criteria = "safe-to-deploy"

[[exemptions.dirs-sys]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.ecdsa]]
version = "0.14.8"
criteria = "safe-to-deploy"

[[exemptions.either]]
version = "1.9.0"
criteria = "safe-to-deploy"

[[exemptions.elliptic-curve]]
version = "0.12.3"
criteria = "safe-to-deploy"

[[exemptions.equivalent]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.fastcdc]]
version = "3.1.0"
criteria = "safe-to-deploy"

[[exemptions.ff]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.fnv]]
version = "1.0.7"
criteria = "safe-to-deploy"

[[exemptions.form_urlencoded]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.fs4]]
version = "0.6.6"
criteria = "safe-to-deploy"

[[exemptions.futures]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-channel]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-executor]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-io]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-macro]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.11"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.28.1"
criteria = "safe-to-deploy"

[[exemptions.group]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.h2]]
version = "0.3.22"
criteria = "safe-to-deploy"

[[exemptions.half]]
version = "1.8.2"
criteria = "safe-to-run"

[[exemptions.heck]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.hex]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.http]]
version = "0.2.11"
criteria = "safe-to-deploy"

[[exemptions.http-body]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.httparse]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.humansize]]
version = "2.1.3"
criteria = "safe-to-deploy"

[[exemptions.hyper]]
version = "0.14.27"
criteria = "safe-to-deploy"

[[exemptions.hyper-rustls]]
version = "0.24.2"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone]]
version = "0.1.58"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone-haiku]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.ident_case]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.idna]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "1.9.3"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.lazy_static]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.151"
criteria = "safe-to-deploy"

[[exemptions.libm]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.libredox]]
version = "0.0.1"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.20"
criteria = "safe-to-deploy"

[[exemptions.lru]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.md-5]]
version = "0.10.6"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "0.8.10"
criteria = "safe-to-deploy"

[[exemptions.num-integer]]
version = "0.1.45"
criteria = "safe-to-deploy"

[[exemptions.num-traits]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.num_cpus]]
version = "1.16.0"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.32.2"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.18.0"
criteria = "safe-to-deploy"

[[exemptions.oorandom]]
version = "11.1.3"
criteria = "safe-to-run"

[[exemptions.option-ext]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.outref]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.p256]]
version = "0.11.1"
criteria = "safe-to-deploy"

[[exemptions.percent-encoding]]
version = "2.3.1"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.pkcs8]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.plotters]]
version = "0.3.5"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.5"
criteria = "safe-to-run"

[[exemptions.plotters-svg]]
version = "0.3.5"
criteria = "safe-to-run"

[[exemptions.powerfmt]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.rayon]]
version = "1.8.0"
criteria = "safe-to-run"

[[exemptions.rayon-core]]
version = "1.12.0"
criteria = "safe-to-run"

[[exemptions.redox_syscall]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.redox_users]]
version = "0.4.4"
criteria = "safe-to-deploy"

[[exemptions.reflink]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.rfc6979]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.17.7"
criteria = "safe-to-deploy"

[[exemptions.rmp]]
version = "0.8.12"
criteria = "safe-to-deploy"

[[exemptions.rmp-serde]]
version = "1.1.2"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.21.10"
criteria = "safe-to-deploy"

[[exemptions.rustls-native-certs]]
version = "0.6.3"
criteria = "safe-to-deploy"

[[exemptions.rustls-pemfile]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.101.7"
criteria = "safe-to-deploy"

[[exemptions.schannel]]
version = "0.1.23"
criteria = "safe-to-deploy"

[[exemptions.sct]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.sec1]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.security-framework]]
version = "2.9.2"
criteria = "safe-to-deploy"

[[exemptions.security-framework-sys]]
version = "2.9.1"
criteria = "safe-to-deploy"

[[exemptions.serde_with]]
version = "3.4.0"
criteria = "safe-to-deploy"

[[exemptions.serde_with_macros]]
version = "3.4.0"
criteria = "safe-to-deploy"

[[exemptions.sha1]]
version = "0.10.6"
criteria = "safe-to-deploy"

[[exemptions.sha2]]
version = "0.10.8"
criteria = "safe-to-deploy"

[[exemptions.signature]]
version = "1.6.4"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.11.2"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.spki]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.subtle]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.9.0"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.time-core]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.time-macros]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.tinytemplate]]
version = "1.2.1"
criteria = "safe-to-run"

[[exemptions.tokio]]
version = "1.35.1"
criteria = "safe-to-deploy"

[[exemptions.tokio-macros]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-rustls]]
version = "0.24.1"
criteria = "safe-to-deploy"

[[exemptions.tokio-util]]
version = "0.7.10"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.40"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.27"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.32"
criteria = "safe-to-deploy"

[[exemptions.tracing-log]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.tracing-test]]
version = "0.2.4"
criteria = "safe-to-run"

[[exemptions.tracing-test-macro]]
version = "0.2.4"
criteria = "safe-to-run"

[[exemptions.typenum]]
version = "1.17.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-bidi]]
version = "0.3.14"
criteria = "safe-to-deploy"

[[exemptions.unicode-normalization]]
version = "0.1.22"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.url]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.urlencoding]]
version = "2.1.3"
criteria = "safe-to-deploy"

[[exemptions.uuid]]
version = "1.6.1"
criteria = "safe-to-deploy"

[[exemptions.valuable]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.vsimd]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.xmlparser]]
version = "0.13.6"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.7.32"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.7.32"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.7.0"
criteria = "safe-to-deploy"
