
# cargo-vet config file

[cargo-vet]
version = "0.8"

[[exemptions.addr2line]]
version = "0.21.0"
criteria = "safe-to-deploy"

[[exemptions.adler]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "1.1.2"
criteria = "safe-to-deploy"

[[exemptions.android-tzdata]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.android_system_properties]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.anstream]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.anstyle]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.anstyle-parse]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.anstyle-query]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.anstyle-wincon]]
version = "3.0.1"
criteria = "safe-to-deploy"

[[exemptions.anyhow]]
version = "1.0.75"
criteria = "safe-to-deploy"

[[exemptions.arrayref]]
version = "0.3.7"
criteria = "safe-to-deploy"

[[exemptions.arrayvec]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.async-compat]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.async-trait]]
version = "0.1.73"
criteria = "safe-to-deploy"

[[exemptions.autocfg]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.aws-config]]
version = "0.56.1"
criteria = "safe-to-deploy"

[[exemptions.aws-credential-types]]
version = "0.56.1"
criteria = "safe-to-deploy"

[[exemptions.aws-http]]
version = "0.56.1"
criteria = "safe-to-deploy"

[[exemptions.aws-runtime]]
version = "0.56.1"
criteria = "safe-to-deploy"

[[exemptions.aws-sdk-dynamodb]]
version = "0.31.1"
criteria = "safe-to-deploy"

[[exemptions.aws-sdk-s3]]
version = "0.31.2"
criteria = "safe-to-deploy"

[[exemptions.aws-sdk-sso]]
version = "0.30.0"
criteria = "safe-to-deploy"

[[exemptions.aws-sdk-sts]]
version = "0.30.0"
criteria = "safe-to-deploy"

[[exemptions.aws-sigv4]]
version = "0.56.1"
criteria = "safe-to-deploy"

[[exemptions.aws-smithy-async]]
version = "0.56.1"
criteria = "safe-to-deploy"

[[exemptions.aws-smithy-checksums]]
version = "0.56.1"
criteria = "safe-to-deploy"

[[exemptions.aws-smithy-client]]
version = "0.56.1"
criteria = "safe-to-deploy"

[[exemptions.aws-smithy-eventstream]]
version = "0.56.1"
criteria = "safe-to-deploy"

[[exemptions.aws-smithy-http]]
version = "0.56.1"
criteria = "safe-to-deploy"

[[exemptions.aws-smithy-http-tower]]
version = "0.56.1"
criteria = "safe-to-deploy"

[[exemptions.aws-smithy-json]]
version = "0.56.1"
criteria = "safe-to-deploy"

[[exemptions.aws-smithy-query]]
version = "0.56.1"
criteria = "safe-to-deploy"

[[exemptions.aws-smithy-runtime]]
version = "0.56.1"
criteria = "safe-to-deploy"

[[exemptions.aws-smithy-runtime-api]]
version = "0.56.1"
criteria = "safe-to-deploy"

[[exemptions.aws-smithy-types]]
version = "0.56.1"
criteria = "safe-to-deploy"

[[exemptions.aws-smithy-xml]]
version = "0.56.1"
criteria = "safe-to-deploy"

[[exemptions.aws-types]]
version = "0.56.1"
criteria = "safe-to-deploy"

[[exemptions.backtrace]]
version = "0.3.69"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.21.4"
criteria = "safe-to-deploy"

[[exemptions.base64-simd]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.4.0"
criteria = "safe-to-deploy"

[[exemptions.blake3]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.block-buffer]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.bumpalo]]
version = "3.14.0"
criteria = "safe-to-deploy"

[[exemptions.byteorder]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.bytes-utils]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.0.83"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.31"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "4.4.6"
criteria = "safe-to-deploy"

[[exemptions.clap_builder]]
version = "4.4.6"
criteria = "safe-to-deploy"

[[exemptions.clap_derive]]
version = "4.4.2"
criteria = "safe-to-deploy"

[[exemptions.clap_lex]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.colorchoice]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.constant_time_eq]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.core-foundation]]
version = "0.9.3"
criteria = "safe-to-deploy"

[[exemptions.core-foundation-sys]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.crc32c]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.crypto-common]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.darling]]
version = "0.20.3"
criteria = "safe-to-deploy"

[[exemptions.darling_core]]
version = "0.20.3"
criteria = "safe-to-deploy"

[[exemptions.darling_macro]]
version = "0.20.3"
criteria = "safe-to-deploy"

[[exemptions.deranged]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.dirs]]
version = "5.0.1"
criteria = "safe-to-deploy"

[[exemptions.dirs-sys]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.either]]
version = "1.9.0"
criteria = "safe-to-deploy"

[[exemptions.equivalent]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.errno]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.fastcdc]]
version = "3.1.0"
criteria = "safe-to-deploy"

[[exemptions.fastrand]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.fnv]]
version = "1.0.7"
criteria = "safe-to-deploy"

[[exemptions.form_urlencoded]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.fs4]]
version = "0.6.6"
criteria = "safe-to-deploy"

[[exemptions.futures]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.futures-channel]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.futures-executor]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.futures-io]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.futures-macro]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.10"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.28.0"
criteria = "safe-to-deploy"

[[exemptions.h2]]
version = "0.3.21"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.12.3"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.14.1"
criteria = "safe-to-deploy"

[[exemptions.heck]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.hex]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.hmac]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.http]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.http-body]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.httparse]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.httpdate]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.humansize]]
version = "2.1.3"
criteria = "safe-to-deploy"

[[exemptions.hyper]]
version = "0.14.27"
criteria = "safe-to-deploy"

[[exemptions.hyper-rustls]]
version = "0.24.1"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone]]
version = "0.1.57"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone-haiku]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.ident_case]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.idna]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "1.9.3"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "2.0.2"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.9"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.64"
criteria = "safe-to-deploy"

[[exemptions.lazy_static]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.149"
criteria = "safe-to-deploy"

[[exemptions.libm]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.4.10"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.10"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.20"
criteria = "safe-to-deploy"

[[exemptions.matchers]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.md-5]]
version = "0.10.6"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.6.4"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "0.8.8"
criteria = "safe-to-deploy"

[[exemptions.nu-ansi-term]]
version = "0.46.0"
criteria = "safe-to-deploy"

[[exemptions.num-integer]]
version = "0.1.45"
criteria = "safe-to-deploy"

[[exemptions.num-traits]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.num_cpus]]
version = "1.16.0"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.32.1"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.18.0"
criteria = "safe-to-deploy"

[[exemptions.openssl-probe]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.option-ext]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.outref]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.overload]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.parking_lot]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.paste]]
version = "1.0.14"
criteria = "safe-to-deploy"

[[exemptions.percent-encoding]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.13"
criteria = "safe-to-deploy"

[[exemptions.pin-utils]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.powerfmt]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.69"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.33"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.redox_users]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.reflink]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.10.1"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.1.10"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.6.29"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.16.20"
criteria = "safe-to-deploy"

[[exemptions.rmp]]
version = "0.8.12"
criteria = "safe-to-deploy"

[[exemptions.rmp-serde]]
version = "1.1.2"
criteria = "safe-to-deploy"

[[exemptions.rustc-demangle]]
version = "0.1.23"
criteria = "safe-to-deploy"

[[exemptions.rustc_version]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "0.38.19"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.21.7"
criteria = "safe-to-deploy"

[[exemptions.rustls-native-certs]]
version = "0.6.3"
criteria = "safe-to-deploy"

[[exemptions.rustls-pemfile]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.101.6"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.15"
criteria = "safe-to-deploy"

[[exemptions.schannel]]
version = "0.1.22"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.sct]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.security-framework]]
version = "2.9.2"
criteria = "safe-to-deploy"

[[exemptions.security-framework-sys]]
version = "2.9.1"
criteria = "safe-to-deploy"

[[exemptions.semver]]
version = "1.0.20"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.189"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.189"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.107"
criteria = "safe-to-deploy"

[[exemptions.serde_with]]
version = "3.3.0"
criteria = "safe-to-deploy"

[[exemptions.serde_with_macros]]
version = "3.3.0"
criteria = "safe-to-deploy"

[[exemptions.sha1]]
version = "0.10.6"
criteria = "safe-to-deploy"

[[exemptions.sha2]]
version = "0.10.8"
criteria = "safe-to-deploy"

[[exemptions.sharded-slab]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.1"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.11.1"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.5.4"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.subtle]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.38"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.8.0"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "1.0.49"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "1.0.49"
criteria = "safe-to-deploy"

[[exemptions.thread_local]]
version = "1.1.7"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.time-core]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.time-macros]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.tinyvec]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.tinyvec_macros]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.33.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-macros]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-rustls]]
version = "0.24.1"
criteria = "safe-to-deploy"

[[exemptions.tokio-stream]]
version = "0.1.14"
criteria = "safe-to-deploy"

[[exemptions.tokio-util]]
version = "0.7.9"
criteria = "safe-to-deploy"

[[exemptions.tower]]
version = "0.4.13"
criteria = "safe-to-deploy"

[[exemptions.tower-layer]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.39"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.27"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.32"
criteria = "safe-to-deploy"

[[exemptions.tracing-log]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.tracing-subscriber]]
version = "0.3.17"
criteria = "safe-to-deploy"

[[exemptions.try-lock]]
version = "0.2.4"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.17.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-bidi]]
version = "0.3.13"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.12"
criteria = "safe-to-deploy"

[[exemptions.unicode-normalization]]
version = "0.1.22"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.url]]
version = "2.4.1"
criteria = "safe-to-deploy"

[[exemptions.urlencoding]]
version = "2.1.3"
criteria = "safe-to-deploy"

[[exemptions.utf8parse]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.uuid]]
version = "1.4.1"
criteria = "safe-to-deploy"

[[exemptions.valuable]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.vsimd]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.want]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.87"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.87"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.87"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.87"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.87"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.64"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.xmlparser]]
version = "0.13.6"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.6.0"
criteria = "safe-to-deploy"
